# SwiftLint Configuration for sysm
# Moderate rules focused on code quality and consistency

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - docs
  - scripts

# Analyzer rules (require compilation)
analyzer_rules:
  - unused_declaration
  - unused_import

# Opt-in rules (not enabled by default)
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  # - file_header  # Disabled: no files use the required header pattern
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo  # Allow TODO comments during development
  - line_length  # Using SwiftFormat for this

# Rule configurations
file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - to
    - by
    - at

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

large_tuple:
  warning: 3
  error: 4

# File header configuration
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  sysm
                    \/\/

# Custom rules
custom_rules:
  no_force_unwrap:
    name: "Avoid force unwraps"
    regex: "(?<!\\?)!(?!\\s*\\})"
    message: "Consider using optional binding or guard statements"
    severity: warning

# Reporter type
reporter: "xcode"
